# -*- coding: utf-8 -*-
"""text classification using zero shot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ro2Eh_y9pUyDRq2fmj37igRtRE-kS3fw
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install torch transformers numpy pandas

from transformers import pipeline
from pprint import pprint
#get a model from huggingface
classifier = pipeline('zero-shot-classification', model = 'Mistral-7B-Instruct-v0.3')