# -*- coding: utf-8 -*-
"""text classification using zero shot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ro2Eh_y9pUyDRq2fmj37igRtRE-kS3fw
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install torch transformers numpy pandas

from google.colab import userdata
userdata.get('modelToken')

from huggingface_hub import snapshot_download
from pathlib import Path

mistral_models_path = Path.home().joinpath('mistral_models', '7B-Instruct-v0.3')
mistral_models_path.mkdir(parents=True, exist_ok=True)

snapshot_download(repo_id="mistralai/Mistral-7B-Instruct-v0.3", allow_patterns=["params.json", "consolidated.safetensors", "tokenizer.model.v3"], local_dir=mistral_models_path)

from transformers import pipeline
from pprint import pprint
#get a model from huggingface
classifier = pipeline('zero-shot-classification', model = 'Mistral-7B-Instruct-v0.3')

# Commented out IPython magic to ensure Python compatibility.
# %pip install mistral_inference

from mistral_inference.transformer import Transformer
from mistral_inference.generate import generate

from mistral_common.tokens.tokenizers.mistral import MistralTokenizer
from mistral_common.protocol.instruct.messages import UserMessage
from mistral_common.protocol.instruct.request import ChatCompletionRequest


tokenizer = MistralTokenizer.from_file(f"{mistral_models_path}/tokenizer.model.v3")
model = Transformer.from_folder(mistral_models_path)

completion_request = ChatCompletionRequest(messages=[UserMessage(content="Explain Stocks and bonds to me")])

tokens = tokenizer.encode_chat_completion(completion_request).tokens

out_tokens, _ = generate([tokens], model, max_tokens=64, temperature=0.0, eos_id=tokenizer.instruct_tokenizer.tokenizer.eos_id)
result = tokenizer.instruct_tokenizer.tokenizer.decode(out_tokens[0])

print(result)





#user input for text

UserInputText = input("Type in the text you would like classified")

SentimentLabels = ['positive', 'negative', 'neutral']
result = classifier(sequence, candidate_labels)

print(result)

sentiment = result['labels'][result['scores'].index(max(result['scores']))]
print(f'\nExtracted Sentiment -> {sentiment}')

sequence_topic = input("Give me some text to classify into some categories")
candidate_topics = ['Technology', 'Health', 'Politics', 'Sports', 'Finance']
result_topic = classifier(sequence_topic, candidate_topics)

topic = result_topic['labels'][result_topic['scores'].index(max(result_topic['scores']))]
print(result_topic)

